language: node_js
node_js:
- 8.9.1
os:
- linux
sudo: false
install:
  - npm install -g travis-ci-cloudfront-invalidation
  - npm install
script:
  - npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: youngk.im
  skip_cleanup: true
  local_dir: public
after_deploy:
- travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY -s $AWS_SECRET_KEY -c $AWS_CLOUDFRONT_DIST_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST